---
title: "Data Analysis Results"
author: "Itir Karac"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_caption: yes
    fig_width: 4
    fig_height: 4
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
```{r setup, include = FALSE}
knitr::opts_chunk$set(
collapse = TRUE,
comment = "#>",
fig.align = "center"
)
```

```{r}
library(reproducerTaskGra)
```

## Participant Demographics

```{r participant_demographics, fig.cap = "Fig. 1: Summary of demographic survey for participants" }
reproduce_barplot_participants()
```

## Statistical Data Analysis

### Functional Correctness

#### Descriptive statistics

```{r descriptive_stats_COR}
knitr::kable(reproduce_descriptive_stats_CORRECTNESS())
```

#### Plots
```{r, fig.cap = "Fig. 2. Violin plots for CORRECTNESS at both levels of Task Description Granularity. Data points are indicated as dots grouped into bins of width 5. Horizontal lines within the plots indicate 0.25, 0.50 and 0.75 quantiles." }
reproduce_violin_plot_CORRECTNESS()
```

```{r, fig.width = 8, fig.cap = "Fig. 3. Boxplots for CORRECTNESS shown separately on different tasks and sequences. Data points are indicated as dots grouped into bins of width 5. Horizontal lines within the plots indicate 0.25, 0.50 and 0.75 quantiles" }
reproduce_boxplot_CORRECTNESS()
```

#### Linear Mixed-effects Model
```{r}
reproduce_lmm_CORRECTNESS()
knitr::kable(reproduce_estimates_CORRECTNESS(), caption = "TABLE 6 Estimates of fixed effects for CORRECTNESS")
```

####  Hypothesis Tests
```{r}
knitr::kable(reproduce_hypothesis_testing_CORRECTNESS(), caption = "TABLE 7 Tests of fixed effects for CORRECTNESS")
```

####  Effect Size


### Functional Completeness

#### Descriptive statistics

```{r descriptive_stats_COMP}
knitr::kable(reproduce_descriptive_stats_COMPLETENESS())
```

#### Plots
```{r, fig.cap = "Fig. 5. Violin plots for COMPLETENESS at both levels of Task Description Granularity. Data points are indicated as dots grouped into bins of width 5. Horizontal lines within the plots indicate 0.25, 0.50 and 0.75 quantiles." }
reproduce_violin_plot_COMPLETENESS()
```

```{r, fig.cap = "Fig. 6. Boxplots for COMPLETENESS shown separately on different tasks and sequences. Data points are indicated as dots grouped into bins of width 5. Horizontal lines within the plots indicate 0.25, 0.50 and 0.75 quantiles" }
reproduce_boxplot_COMPLETENESS()
```


([Project Website](http://eatdd.oulu.fi))
